import type { Metadata } from "next";
import "./globals.css";
import {ReactNode} from "react";
import {getLocale, getMessages} from "next-intl/server";
import {NextIntlClientProvider} from "next-intl";
import AppStoreProvider from "@/app/_providers/AppStoreProvider";
import AppQueryClientProvider from "@/app/_providers/AppQueryClientProvider";
import {ToastContainer} from "react-toastify";
import {ClerkProvider} from "@clerk/nextjs";
import {bgBG, enUS} from "@clerk/localizations";
import ThemeProvider from "@/app/_providers/ThemeProvider";
import {dark} from "@clerk/themes";
import ClerkAuthProvider from "@/app/_providers/ClerkAuthProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type LayoutProps = {
    children: ReactNode
}

export default async function RootLayout({
  children,
}: Readonly<LayoutProps>) {
    const locale = await getLocale()
    const messages = await getMessages();

    return (
        <html lang={locale} suppressHydrationWarning={true}>
        <NextIntlClientProvider messages={messages}>
            <AppStoreProvider>
                <AppQueryClientProvider>
                    <body>
                        <ThemeProvider
                            attribute="class"
                            defaultTheme="system"
                            enableSystem={true}
                            disableTransitionOnChange={true}
                        >
                            <ClerkAuthProvider locale={locale}>
                                {children}
                                <ToastContainer />
                            </ClerkAuthProvider>
                        </ThemeProvider>
                    </body>
                </AppQueryClientProvider>
            </AppStoreProvider>
        </NextIntlClientProvider>
        </html>
    );
}
