import type { Metadata } from "next";
import "./globals.css";
import {ReactNode} from "react";
import {getLocale, getMessages} from "next-intl/server";
import {NextIntlClientProvider} from "next-intl";
import AppStoreProvider from "@/app/_providers/AppStoreProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type LayoutProps = {
    children: ReactNode
}

export default async function RootLayout({
  children,
}: Readonly<LayoutProps>) {
    const locale = await getLocale()
    const messages = await getMessages();

    return (
        <html lang={locale}>
        <NextIntlClientProvider messages={messages}>
            <AppStoreProvider>
                <body>
                {children}
                </body>
            </AppStoreProvider>
        </NextIntlClientProvider>
        </html>
    );
}
